export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const PURCHASE_FAIL = "PURCHASE_FAIL"

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL"
export const FETCH_ORDERS_START = "FETCH_ORDERS_START"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
